spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tradenova}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

tradenova:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds: 3600000

kis:
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}